export const countries = [
  {
     "name":"Afeganistão",
     "codeISOAlphaTwo":"AF",
     "codeISOAlphaThree":"AFG",
     "codeISONumber":"0132"
  },
  {
     "name":"África do Sul",
     "codeISOAlphaTwo":"ZA",
     "codeISOAlphaThree":"ZAF",
     "codeISONumber":"7560"
  },
  {
     "name":"Albânia",
     "codeISOAlphaTwo":"AL",
     "codeISOAlphaThree":"ALB",
     "codeISONumber":"0175"
  },
  {
     "name":"Alemanha",
     "codeISOAlphaTwo":"DE",
     "codeISOAlphaThree":"DEU",
     "codeISONumber":"0230"
  },
  {
     "name":"Andora",
     "codeISOAlphaTwo":"AD",
     "codeISOAlphaThree":"AND",
     "codeISONumber":"0370"
  },
  {
     "name":"Angola",
     "codeISOAlphaTwo":"AO",
     "codeISOAlphaThree":"AGO",
     "codeISONumber":"0400"
  },
  {
     "name":"Anguilla",
     "codeISOAlphaTwo":"AI",
     "codeISOAlphaThree":"AIA",
     "codeISONumber":"0418"
  },
  {
     "name":"Antarctica",
     "codeISOAlphaTwo":"AQ",
     "codeISOAlphaThree":"ATA",
     "codeISONumber":"0000"
  },
  {
     "name":"Antígua e Barbuda",
     "codeISOAlphaTwo":"AG",
     "codeISOAlphaThree":"ATG",
     "codeISONumber":"0434"
  },
  {
     "name":"Antilhas Holandesas",
     "codeISOAlphaTwo":"AN",
     "codeISOAlphaThree":"ANT",
     "codeISONumber":"0477"
  },
  {
     "name":"Arábia Saudita",
     "codeISOAlphaTwo":"SA",
     "codeISOAlphaThree":"SAU",
     "codeISONumber":"0531"
  },
  {
     "name":"Argélia",
     "codeISOAlphaTwo":"DZ",
     "codeISOAlphaThree":"DZA",
     "codeISONumber":"0590"
  },
  {
     "name":"Argentina",
     "codeISOAlphaTwo":"AR",
     "codeISOAlphaThree":"ARG",
     "codeISONumber":"0639"
  },
  {
     "name":"Arménia",
     "codeISOAlphaTwo":"AM",
     "codeISOAlphaThree":"ARM",
     "codeISONumber":"0647"
  },
  {
     "name":"Aruba",
     "codeISOAlphaTwo":"AW",
     "codeISOAlphaThree":"ABW",
     "codeISONumber":"0655"
  },
  {
     "name":"Austrália",
     "codeISOAlphaTwo":"AU",
     "codeISOAlphaThree":"AUS",
     "codeISONumber":"0698"
  },
  {
     "name":"Áustria",
     "codeISOAlphaTwo":"AT",
     "codeISOAlphaThree":"AUT",
     "codeISONumber":"0728"
  },
  {
     "name":"Azerbaijão",
     "codeISOAlphaTwo":"AZ",
     "codeISOAlphaThree":"AZE",
     "codeISONumber":"0736"
  },
  {
     "name":"Bahamas",
     "codeISOAlphaTwo":"BS",
     "codeISOAlphaThree":"BHS",
     "codeISONumber":"0779"
  },
  {
     "name":"Bahrein",
     "codeISOAlphaTwo":"BH",
     "codeISOAlphaThree":"BHR",
     "codeISONumber":"0809"
  },
  {
     "name":"Bangladesh",
     "codeISOAlphaTwo":"BD",
     "codeISOAlphaThree":"BGD",
     "codeISONumber":"0817"
  },
  {
     "name":"Barbados",
     "codeISOAlphaTwo":"BB",
     "codeISOAlphaThree":"BRB",
     "codeISONumber":"0833"
  },
  {
     "name":"Bélgica",
     "codeISOAlphaTwo":"BE",
     "codeISOAlphaThree":"BEL",
     "codeISONumber":"0876"
  },
  {
     "name":"Belize",
     "codeISOAlphaTwo":"BZ",
     "codeISOAlphaThree":"BLZ",
     "codeISONumber":"0884"
  },
  {
     "name":"Benim",
     "codeISOAlphaTwo":"BJ",
     "codeISOAlphaThree":"BEN",
     "codeISONumber":"2291"
  },
  {
     "name":"Bermuda",
     "codeISOAlphaTwo":"BM",
     "codeISOAlphaThree":"BMU",
     "codeISONumber":"0906"
  },
  {
     "name":"Bielorrússia",
     "codeISOAlphaTwo":"BY",
     "codeISOAlphaThree":"BLR",
     "codeISONumber":"0000"
  },
  {
     "name":"Bolívia",
     "codeISOAlphaTwo":"BO",
     "codeISOAlphaThree":"BOL",
     "codeISONumber":"0973"
  },
  {
     "name":"Bósnia e Herzegovina",
     "codeISOAlphaTwo":"BA",
     "codeISOAlphaThree":"BIH",
     "codeISONumber":"0981"
  },
  {
     "name":"Botswana",
     "codeISOAlphaTwo":"BW",
     "codeISOAlphaThree":"BWA",
     "codeISONumber":"1015"
  },
  {
     "name":"Brasil",
     "codeISOAlphaTwo":"BR",
     "codeISOAlphaThree":"BRA",
     "codeISONumber":"1058"
  },
  {
     "name":"Brunei",
     "codeISOAlphaTwo":"BN",
     "codeISOAlphaThree":"BRN",
     "codeISONumber":"1082"
  },
  {
     "name":"Bulgária",
     "codeISOAlphaTwo":"BG",
     "codeISOAlphaThree":"BGR",
     "codeISONumber":"1112"
  },
  {
     "name":"Burkina Faso",
     "codeISOAlphaTwo":"BF",
     "codeISOAlphaThree":"BFA",
     "codeISONumber":"0310"
  },
  {
     "name":"Burundi",
     "codeISOAlphaTwo":"BI",
     "codeISOAlphaThree":"BDI",
     "codeISONumber":"1155"
  },
  {
     "name":"Butão",
     "codeISOAlphaTwo":"BT",
     "codeISOAlphaThree":"BTN",
     "codeISONumber":"1198"
  },
  {
     "name":"Cabo Verde",
     "codeISOAlphaTwo":"CV",
     "codeISOAlphaThree":"CPV",
     "codeISONumber":"1279"
  },
  {
     "name":"Camarões",
     "codeISOAlphaTwo":"CM",
     "codeISOAlphaThree":"CMR",
     "codeISONumber":"1457"
  },
  {
     "name":"Camboja",
     "codeISOAlphaTwo":"KH",
     "codeISOAlphaThree":"KHM",
     "codeISONumber":"1414"
  },
  {
     "name":"Canadá",
     "codeISOAlphaTwo":"CA",
     "codeISOAlphaThree":"CAN",
     "codeISONumber":"1490"
  },
  {
     "name":"Catar",
     "codeISOAlphaTwo":"QA",
     "codeISOAlphaThree":"QAT",
     "codeISONumber":"1546"
  },
  {
     "name":"Cazaquistão",
     "codeISOAlphaTwo":"KZ",
     "codeISOAlphaThree":"KAZ",
     "codeISONumber":"1538"
  },
  {
     "name":"Chad",
     "codeISOAlphaTwo":"TD",
     "codeISOAlphaThree":"TCD",
     "codeISONumber":"7889"
  },
  {
     "name":"Chile",
     "codeISOAlphaTwo":"CL",
     "codeISOAlphaThree":"CHL",
     "codeISONumber":"1589"
  },
  {
     "name":"China",
     "codeISOAlphaTwo":"CN",
     "codeISOAlphaThree":"CHN",
     "codeISONumber":"1600"
  },
  {
     "name":"Chipre",
     "codeISOAlphaTwo":"CY",
     "codeISOAlphaThree":"CYP",
     "codeISONumber":"1635"
  },
  {
     "name":"Christmas Island",
     "codeISOAlphaTwo":"CX",
     "codeISOAlphaThree":"CXR",
     "codeISONumber":"5118"
  },
  {
     "name":"Cingapura",
     "codeISOAlphaTwo":"SG",
     "codeISOAlphaThree":"SGP",
     "codeISONumber":"7412"
  },
  {
     "name":"Colômbia",
     "codeISOAlphaTwo":"CO",
     "codeISOAlphaThree":"COL",
     "codeISONumber":"1694"
  },
  {
     "name":"Comores",
     "codeISOAlphaTwo":"KM",
     "codeISOAlphaThree":"COM",
     "codeISONumber":"1732"
  },
  {
     "name":"Coreia do Sul",
     "codeISOAlphaTwo":"KR",
     "codeISOAlphaThree":"KOR",
     "codeISONumber":"1902"
  },
  {
     "name":"Costa do Marfim",
     "codeISOAlphaTwo":"CI",
     "codeISOAlphaThree":"CIV",
     "codeISONumber":"1937"
  },
  {
     "name":"Costa Rica",
     "codeISOAlphaTwo":"CR",
     "codeISOAlphaThree":"CRC",
     "codeISONumber":"1961"
  },
  {
     "name":"Croácia",
     "codeISOAlphaTwo":"HR",
     "codeISOAlphaThree":"HRV",
     "codeISONumber":"1953"
  },
  {
     "name":"Cuba",
     "codeISOAlphaTwo":"CU",
     "codeISOAlphaThree":"CUB",
     "codeISONumber":"1996"
  },
  {
     "name":"Dinamarca",
     "codeISOAlphaTwo":"DK",
     "codeISOAlphaThree":"DNK",
     "codeISONumber":"2321"
  },
  {
     "name":"Djibouti",
     "codeISOAlphaTwo":"DJ",
     "codeISOAlphaThree":"DJI",
     "codeISONumber":"7838"
  },
  {
     "name":"Dominica",
     "codeISOAlphaTwo":"DM",
     "codeISOAlphaThree":"DMA",
     "codeISONumber":"2356"
  },
  {
     "name":"Egito",
     "codeISOAlphaTwo":"EG",
     "codeISOAlphaThree":"EGY",
     "codeISONumber":"2402"
  },
  {
     "name":"El Salvador",
     "codeISOAlphaTwo":"SV",
     "codeISOAlphaThree":"SLV",
     "codeISONumber":"6874"
  },
  {
     "name":"Emirados Árabes Unidos",
     "codeISOAlphaTwo":"AE",
     "codeISOAlphaThree":"ARE",
     "codeISONumber":"2445"
  },
  {
     "name":"Equador",
     "codeISOAlphaTwo":"EC",
     "codeISOAlphaThree":"ECU",
     "codeISONumber":"2399"
  },
  {
     "name":"Eritreia",
     "codeISOAlphaTwo":"ER",
     "codeISOAlphaThree":"ERI",
     "codeISONumber":"2437"
  },
  {
     "name":"Espanha",
     "codeISOAlphaTwo":"ES",
     "codeISOAlphaThree":"ESP",
     "codeISONumber":"2453"
  },
  {
     "name":"Estados Unidos (EUA)",
     "codeISOAlphaTwo":"US",
     "codeISOAlphaThree":"USA",
     "codeISONumber":"2496"
  },
  {
     "name":"Estónia",
     "codeISOAlphaTwo":"EE",
     "codeISOAlphaThree":"EST",
     "codeISONumber":"2518"
  },
  {
     "name":"Etiópia",
     "codeISOAlphaTwo":"ET",
     "codeISOAlphaThree":"ETH",
     "codeISONumber":"2534"
  },
  {
     "name":"Fiji",
     "codeISOAlphaTwo":"FJ",
     "codeISOAlphaThree":"FJI",
     "codeISONumber":"8702"
  },
  {
     "name":"Filipinas",
     "codeISOAlphaTwo":"PH",
     "codeISOAlphaThree":"PHL",
     "codeISONumber":"2674"
  },
  {
     "name":"Finlândia",
     "codeISOAlphaTwo":"FI",
     "codeISOAlphaThree":"FIN",
     "codeISONumber":"2712"
  },
  {
     "name":"França",
     "codeISOAlphaTwo":"FR",
     "codeISOAlphaThree":"FRA",
     "codeISONumber":"2755"
  },
  {
     "name":"Gabão",
     "codeISOAlphaTwo":"GA",
     "codeISOAlphaThree":"GAB",
     "codeISONumber":"2810"
  },
  {
     "name":"Gâmbia",
     "codeISOAlphaTwo":"GM",
     "codeISOAlphaThree":"GMB",
     "codeISONumber":"2852"
  },
  {
     "name":"Gana",
     "codeISOAlphaTwo":"GH",
     "codeISOAlphaThree":"GHA",
     "codeISONumber":"2895"
  },
  {
     "name":"Geórgia",
     "codeISOAlphaTwo":"GE",
     "codeISOAlphaThree":"GEO",
     "codeISONumber":"2917"
  },
  {
     "name":"Gibraltar",
     "codeISOAlphaTwo":"GI",
     "codeISOAlphaThree":"GIB",
     "codeISONumber":"2933"
  },
  {
     "name":"Granada",
     "codeISOAlphaTwo":"GD",
     "codeISOAlphaThree":"GRD",
     "codeISONumber":"2976"
  },
  {
     "name":"Grécia",
     "codeISOAlphaTwo":"GR",
     "codeISOAlphaThree":"GRC",
     "codeISONumber":"3018"
  },
  {
     "name":"Groelândia",
     "codeISOAlphaTwo":"GL",
     "codeISOAlphaThree":"GRL",
     "codeISONumber":"3050"
  },
  {
     "name":"Guam",
     "codeISOAlphaTwo":"GU",
     "codeISOAlphaThree":"GUM",
     "codeISONumber":"3131"
  },
  {
     "name":"Guatemala",
     "codeISOAlphaTwo":"GT",
     "codeISOAlphaThree":"GTM",
     "codeISONumber":"3174"
  },
  {
     "name":"Guiana",
     "codeISOAlphaTwo":"GY",
     "codeISOAlphaThree":"GUY",
     "codeISONumber":"3379"
  },
  {
     "name":"Guiné",
     "codeISOAlphaTwo":"GN",
     "codeISOAlphaThree":"GIN",
     "codeISONumber":"3298"
  },
  {
     "name":"Guiné Equatorial",
     "codeISOAlphaTwo":"GQ",
     "codeISOAlphaThree":"GNQ",
     "codeISONumber":"3310"
  },
  {
     "name":"Guiné-Bissau",
     "codeISOAlphaTwo":"GW",
     "codeISOAlphaThree":"GNB",
     "codeISONumber":"3344"
  },
  {
     "name":"Haiti",
     "codeISOAlphaTwo":"HT",
     "codeISOAlphaThree":"HTI",
     "codeISONumber":"3417"
  },
  {
     "name":"Honduras",
     "codeISOAlphaTwo":"HN",
     "codeISOAlphaThree":"HND",
     "codeISONumber":"3450"
  },
  {
     "name":"Hong Kong",
     "codeISOAlphaTwo":"HK",
     "codeISOAlphaThree":"HKG",
     "codeISONumber":"3514"
  },
  {
     "name":"Hungria",
     "codeISOAlphaTwo":"HU",
     "codeISOAlphaThree":"HUN",
     "codeISONumber":"3557"
  },
  {
     "name":"Iémen (Iémen, Yemen)",
     "codeISOAlphaTwo":"YE",
     "codeISOAlphaThree":"YEM",
     "codeISONumber":"3573"
  },
  {
     "name":"Ilha de Man",
     "codeISOAlphaTwo":"IM",
     "codeISOAlphaThree":"IMN",
     "codeISONumber":"3595"
  },
  {
     "name":"Ilhas Cayman",
     "codeISOAlphaTwo":"KY",
     "codeISOAlphaThree":"CYM",
     "codeISONumber":"1376"
  },
  {
     "name":"Ilhas Cocos (Keeling)",
     "codeISOAlphaTwo":"CC",
     "codeISOAlphaThree":"CCK",
     "codeISONumber":"1651"
  },
  {
     "name":"Ilhas Cook",
     "codeISOAlphaTwo":"CK",
     "codeISOAlphaThree":"COK",
     "codeISONumber":"1830"
  },
  {
     "name":"Ilhas Falkland (Malvinas)",
     "codeISOAlphaTwo":"FK",
     "codeISOAlphaThree":"FLK",
     "codeISONumber":"2550"
  },
  {
     "name":"Ilhas Feroé",
     "codeISOAlphaTwo":"FO",
     "codeISOAlphaThree":"FRO",
     "codeISONumber":"2593"
  },
  {
     "name":"Ilhas Mariana do Norte",
     "codeISOAlphaTwo":"MP",
     "codeISOAlphaThree":"MNP",
     "codeISONumber":"4723"
  },
  {
     "name":"Ilhas Marshall",
     "codeISOAlphaTwo":"MH",
     "codeISOAlphaThree":"MHL",
     "codeISONumber":"4766"
  },
  {
     "name":"Ilhas Pitcairn",
     "codeISOAlphaTwo":"PN",
     "codeISOAlphaThree":"PCN",
     "codeISONumber":"5932"
  },
  {
     "name":"Ilhas Salomão",
     "codeISOAlphaTwo":"SB",
     "codeISOAlphaThree":"SLB",
     "codeISONumber":"6777"
  },
  {
     "name":"Ilhas Turcas e Caicos",
     "codeISOAlphaTwo":"TC",
     "codeISOAlphaThree":"TCA",
     "codeISONumber":"8230"
  },
  {
     "name":"Ilhas Virgens Americanas",
     "codeISOAlphaTwo":"VI",
     "codeISOAlphaThree":"VIR",
     "codeISONumber":"8664"
  },
  {
     "name":"Ilhas Virgens Britânicas",
     "codeISOAlphaTwo":"VG",
     "codeISOAlphaThree":"VGB",
     "codeISONumber":"8630"
  },
  {
     "name":"India",
     "codeISOAlphaTwo":"IN",
     "codeISOAlphaThree":"IND",
     "codeISONumber":"3611"
  },
  {
     "name":"Indonésia",
     "codeISOAlphaTwo":"ID",
     "codeISOAlphaThree":"IDN",
     "codeISONumber":"3654"
  },
  {
     "name":"Inglaterra (Reino Unido)",
     "codeISOAlphaTwo":"GB",
     "codeISOAlphaThree":"GBR",
     "codeISONumber":"6289"
  },
  {
     "name":"Iraque",
     "codeISOAlphaTwo":"IQ",
     "codeISOAlphaThree":"IRQ",
     "codeISONumber":"3697"
  },
  {
     "name":"Irlanda",
     "codeISOAlphaTwo":"IE",
     "codeISOAlphaThree":"IRL",
     "codeISONumber":"3751"
  },
  {
     "name":"Islândia",
     "codeISOAlphaTwo":"IS",
     "codeISOAlphaThree":"IS",
     "codeISONumber":"3794"
  },
  {
     "name":"Israel",
     "codeISOAlphaTwo":"IL",
     "codeISOAlphaThree":"ISR",
     "codeISONumber":"3832"
  },
  {
     "name":"Itália",
     "codeISOAlphaTwo":"IT",
     "codeISOAlphaThree":"ITA",
     "codeISONumber":"3867"
  },
  {
     "name":"Jamaica",
     "codeISOAlphaTwo":"JM",
     "codeISOAlphaThree":"JAM",
     "codeISONumber":"3913"
  },
  {
     "name":"Japão",
     "codeISOAlphaTwo":"JP",
     "codeISOAlphaThree":"JPN",
     "codeISONumber":"3999"
  },
  {
     "name":"Jordânia",
     "codeISOAlphaTwo":"JO",
     "codeISOAlphaThree":"JOR",
     "codeISONumber":"4030"
  },
  {
     "name":"Kiribati",
     "codeISOAlphaTwo":"KI",
     "codeISOAlphaThree":"KIR",
     "codeISONumber":"4111"
  },
  {
     "name":"Kuwait",
     "codeISOAlphaTwo":"KW",
     "codeISOAlphaThree":"KWT",
     "codeISONumber":"1988"
  },
  {
     "name":"Laos",
     "codeISOAlphaTwo":"LA",
     "codeISOAlphaThree":"LAO",
     "codeISONumber":"4200"
  },
  {
     "name":"Lesoto",
     "codeISOAlphaTwo":"LS",
     "codeISOAlphaThree":"LSO",
     "codeISONumber":"4260"
  },
  {
     "name":"Letônia",
     "codeISOAlphaTwo":"LV",
     "codeISOAlphaThree":"LVA",
     "codeISONumber":"4278"
  },
  {
     "name":"Líbano",
     "codeISOAlphaTwo":"LB",
     "codeISOAlphaThree":"LBN",
     "codeISONumber":"4316"
  },
  {
     "name":"Libéria",
     "codeISOAlphaTwo":"LR",
     "codeISOAlphaThree":"LBR",
     "codeISONumber":"4340"
  },
  {
     "name":"Líbia",
     "codeISOAlphaTwo":"LY",
     "codeISOAlphaThree":"LBY",
     "codeISONumber":"4383"
  },
  {
     "name":"Liechtenstein",
     "codeISOAlphaTwo":"LI",
     "codeISOAlphaThree":"LIE",
     "codeISONumber":"4405"
  },
  {
     "name":"Lituânia",
     "codeISOAlphaTwo":"LT",
     "codeISOAlphaThree":"LTU",
     "codeISONumber":"4421"
  },
  {
     "name":"Luxemburgo",
     "codeISOAlphaTwo":"LU",
     "codeISOAlphaThree":"LUX",
     "codeISONumber":"4456"
  },
  {
     "name":"Macau",
     "codeISOAlphaTwo":"MO",
     "codeISOAlphaThree":"MAC",
     "codeISONumber":"4472"
  },
  {
     "name":"Macedónia",
     "codeISOAlphaTwo":"MK",
     "codeISOAlphaThree":"MKD",
     "codeISONumber":"4499"
  },
  {
     "name":"Madagáscar",
     "codeISOAlphaTwo":"MG",
     "codeISOAlphaThree":"MDG",
     "codeISONumber":"4502"
  },
  {
     "name":"Malásia",
     "codeISOAlphaTwo":"MY",
     "codeISOAlphaThree":"MYS",
     "codeISONumber":"4553"
  },
  {
     "name":"Malawi",
     "codeISOAlphaTwo":"MW",
     "codeISOAlphaThree":"MWI",
     "codeISONumber":"4588"
  },
  {
     "name":"Maldivas",
     "codeISOAlphaTwo":"MV",
     "codeISOAlphaThree":"MDV",
     "codeISONumber":"4618"
  },
  {
     "name":"Mali",
     "codeISOAlphaTwo":"ML",
     "codeISOAlphaThree":"MLI",
     "codeISONumber":"4642"
  },
  {
     "name":"Malta",
     "codeISOAlphaTwo":"MT",
     "codeISOAlphaThree":"MLT",
     "codeISONumber":"4677"
  },
  {
     "name":"Marrocos",
     "codeISOAlphaTwo":"MA",
     "codeISOAlphaThree":"MAR",
     "codeISONumber":"4740"
  },
  {
     "name":"Maurícia",
     "codeISOAlphaTwo":"MU",
     "codeISOAlphaThree":"MUS",
     "codeISONumber":"4855"
  },
  {
     "name":"Mauritânia",
     "codeISOAlphaTwo":"MR",
     "codeISOAlphaThree":"MRT",
     "codeISONumber":"4880"
  },
  {
     "name":"Mayotte",
     "codeISOAlphaTwo":"YT",
     "codeISOAlphaThree":"MYT",
     "codeISONumber":"0000"
  },
  {
     "name":"México",
     "codeISOAlphaTwo":"MX",
     "codeISOAlphaThree":"MEX",
     "codeISONumber":"4936"
  },
  {
     "name":"Micronésia",
     "codeISOAlphaTwo":"FM",
     "codeISOAlphaThree":"FSM",
     "codeISONumber":"4995"
  },
  {
     "name":"Moçambique",
     "codeISOAlphaTwo":"MZ",
     "codeISOAlphaThree":"MOZ",
     "codeISONumber":"5053"
  },
  {
     "name":"Moldávia",
     "codeISOAlphaTwo":"MD",
     "codeISOAlphaThree":"MDA",
     "codeISONumber":"4944"
  },
  {
     "name":"Monaco",
     "codeISOAlphaTwo":"MC",
     "codeISOAlphaThree":"MCO",
     "codeISONumber":"4952"
  },
  {
     "name":"Mongólia",
     "codeISOAlphaTwo":"MN",
     "codeISOAlphaThree":"MNG",
     "codeISONumber":"4979"
  },
  {
     "name":"Montenegro",
     "codeISOAlphaTwo":"ME",
     "codeISOAlphaThree":"MNE",
     "codeISONumber":"0000"
  },
  {
     "name":"Montserrat",
     "codeISOAlphaTwo":"MS",
     "codeISOAlphaThree":"MSR",
     "codeISONumber":"5010"
  },
  {
     "name":"Myanmar (Burma)",
     "codeISOAlphaTwo":"MM",
     "codeISOAlphaThree":"MMR",
     "codeISONumber":"0930"
  },
  {
     "name":"Namíbia",
     "codeISOAlphaTwo":"NA",
     "codeISOAlphaThree":"NAM",
     "codeISONumber":"5070"
  },
  {
     "name":"Nauru",
     "codeISOAlphaTwo":"NR",
     "codeISOAlphaThree":"NRU",
     "codeISONumber":"5088"
  },
  {
     "name":"Nepal",
     "codeISOAlphaTwo":"NP",
     "codeISOAlphaThree":"NPL",
     "codeISONumber":"5177"
  },
  {
     "name":"Nicaragua",
     "codeISOAlphaTwo":"NI",
     "codeISOAlphaThree":"NIC",
     "codeISONumber":"5215"
  },
  {
     "name":"Níger",
     "codeISOAlphaTwo":"NE",
     "codeISOAlphaThree":"NER",
     "codeISONumber":"5258"
  },
  {
     "name":"Nigéria",
     "codeISOAlphaTwo":"NG",
     "codeISOAlphaThree":"NGA",
     "codeISONumber":"5282"
  },
  {
     "name":"Niue",
     "codeISOAlphaTwo":"NU",
     "codeISOAlphaThree":"NIU",
     "codeISONumber":"5312"
  },
  {
     "name":"Noruega",
     "codeISOAlphaTwo":"NO",
     "codeISOAlphaThree":"NOR",
     "codeISONumber":"5380"
  },
  {
     "name":"Nova Caledônia",
     "codeISOAlphaTwo":"NC",
     "codeISOAlphaThree":"NCL",
     "codeISONumber":"5428"
  },
  {
     "name":"Nova Zelândia",
     "codeISOAlphaTwo":"NZ",
     "codeISOAlphaThree":"NZL",
     "codeISONumber":"5487"
  },
  {
     "name":"Omã",
     "codeISOAlphaTwo":"OM",
     "codeISOAlphaThree":"OMN",
     "codeISONumber":"5568"
  },
  {
     "name":"Países Baixos",
     "codeISOAlphaTwo":"NL",
     "codeISOAlphaThree":"NLD",
     "codeISONumber":"5738"
  },
  {
     "name":"Palau",
     "codeISOAlphaTwo":"PW",
     "codeISOAlphaThree":"PLW",
     "codeISONumber":"5754"
  },
  {
     "name":"Panamá",
     "codeISOAlphaTwo":"PA",
     "codeISOAlphaThree":"PAN",
     "codeISONumber":"5800"
  },
  {
     "name":"Papua-Nova Guiné",
     "codeISOAlphaTwo":"PG",
     "codeISOAlphaThree":"PNG",
     "codeISONumber":"5452"
  },
  {
     "name":"Paquistão",
     "codeISOAlphaTwo":"PK",
     "codeISOAlphaThree":"PAK",
     "codeISONumber":"5762"
  },
  {
     "name":"Paraguai",
     "codeISOAlphaTwo":"PY",
     "codeISOAlphaThree":"PRY",
     "codeISONumber":"5860"
  },
  {
     "name":"Peru",
     "codeISOAlphaTwo":"PE",
     "codeISOAlphaThree":"PER",
     "codeISONumber":"5894"
  },
  {
     "name":"Polinésia Francesa",
     "codeISOAlphaTwo":"PF",
     "codeISOAlphaThree":"PYF",
     "codeISONumber":"5991"
  },
  {
     "name":"Polónia",
     "codeISOAlphaTwo":"PL",
     "codeISOAlphaThree":"POL",
     "codeISONumber":"6033"
  },
  {
     "name":"Porto Rico",
     "codeISOAlphaTwo":"PR",
     "codeISOAlphaThree":"PRI",
     "codeISONumber":"6114"
  },
  {
     "name":"Portugal",
     "codeISOAlphaTwo":"PT",
     "codeISOAlphaThree":"PRT",
     "codeISONumber":"6076"
  },
  {
     "name":"Quénia (Kenya)",
     "codeISOAlphaTwo":"KE",
     "codeISOAlphaThree":"KEN",
     "codeISONumber":"6238"
  },
  {
     "name":"Quirguistão",
     "codeISOAlphaTwo":"KG",
     "codeISOAlphaThree":"KGZ",
     "codeISONumber":"6254"
  },
  {
     "name":"República Centro-Africana",
     "codeISOAlphaTwo":"CF",
     "codeISOAlphaThree":"CAF",
     "codeISONumber":"6408"
  },
  {
     "name":"República Checa",
     "codeISOAlphaTwo":"CZ",
     "codeISOAlphaThree":"CZE",
     "codeISONumber":"7919"
  },
  {
     "name":"República Democrática do Congo",
     "codeISOAlphaTwo":"CD",
     "codeISOAlphaThree":"COD",
     "codeISONumber":"8885"
  },
  {
     "name":"República do Congo",
     "codeISOAlphaTwo":"CG",
     "codeISOAlphaThree":"COG",
     "codeISONumber":"1775"
  },
  {
     "name":"República Dominicana",
     "codeISOAlphaTwo":"DO",
     "codeISOAlphaThree":"DOM",
     "codeISONumber":"6475"
  },
  {
     "name":"Roménia",
     "codeISOAlphaTwo":"RO",
     "codeISOAlphaThree":"ROU",
     "codeISONumber":"6700"
  },
  {
     "name":"Ruanda",
     "codeISOAlphaTwo":"RW",
     "codeISOAlphaThree":"RWA",
     "codeISONumber":"6750"
  },
  {
     "name":"Rússia",
     "codeISOAlphaTwo":"RU",
     "codeISOAlphaThree":"RUS",
     "codeISONumber":"6769"
  },
  {
     "name":"Saint Barthelemy",
     "codeISOAlphaTwo":"BL",
     "codeISOAlphaThree":"BLM",
     "codeISONumber":"0000"
  },
  {
     "name":"Saint Helena",
     "codeISOAlphaTwo":"SH",
     "codeISOAlphaThree":"SHN",
     "codeISONumber":"7102"
  },
  {
     "name":"Saint Kitts and Nevis",
     "codeISOAlphaTwo":"KN",
     "codeISOAlphaThree":"KNA",
     "codeISONumber":"6955"
  },
  {
     "name":"Saint Lucia",
     "codeISOAlphaTwo":"LC",
     "codeISOAlphaThree":"LCA",
     "codeISONumber":"7153"
  },
  {
     "name":"Saint Martin",
     "codeISOAlphaTwo":"MF",
     "codeISOAlphaThree":"MAF",
     "codeISONumber":"0000"
  },
  {
     "name":"Saint Pierre and Miquelon",
     "codeISOAlphaTwo":"PM",
     "codeISOAlphaThree":"SPM",
     "codeISONumber":"7005"
  },
  {
     "name":"Saint Vincent and the Grenadines",
     "codeISOAlphaTwo":"VC",
     "codeISOAlphaThree":"VCT",
     "codeISONumber":"7056"
  },
  {
     "name":"Samoa",
     "codeISOAlphaTwo":"WS",
     "codeISOAlphaThree":"WSM",
     "codeISONumber":"6904"
  },
  {
     "name":"Samoa Americana",
     "codeISOAlphaTwo":"AS",
     "codeISOAlphaThree":"ASM",
     "codeISONumber":"6912"
  },
  {
     "name":"San Marino",
     "codeISOAlphaTwo":"SM",
     "codeISOAlphaThree":"SMR",
     "codeISONumber":"6971"
  },
  {
     "name":"Sao Tome e Principe",
     "codeISOAlphaTwo":"ST",
     "codeISOAlphaThree":"STP",
     "codeISONumber":"7200"
  },
  {
     "name":"Senegal",
     "codeISOAlphaTwo":"SN",
     "codeISOAlphaThree":"SEN",
     "codeISONumber":"7285"
  },
  {
     "name":"Serbia",
     "codeISOAlphaTwo":"RS",
     "codeISOAlphaThree":"SRB",
     "codeISONumber":"7370"
  },
  {
     "name":"Serra Leoa",
     "codeISOAlphaTwo":"SL",
     "codeISOAlphaThree":"SLE",
     "codeISONumber":"7358"
  },
  {
     "name":"Seychelles",
     "codeISOAlphaTwo":"SC",
     "codeISOAlphaThree":"SYC",
     "codeISONumber":"7315"
  },
  {
     "name":"Slovakia",
     "codeISOAlphaTwo":"SK",
     "codeISOAlphaThree":"SVK",
     "codeISONumber":"2470"
  },
  {
     "name":"Slovenia",
     "codeISOAlphaTwo":"SI",
     "codeISOAlphaThree":"SVN",
     "codeISONumber":"2461"
  },
  {
     "name":"Somalia",
     "codeISOAlphaTwo":"SO",
     "codeISOAlphaThree":"SOM",
     "codeISONumber":"7480"
  },
  {
     "name":"Sri Lanka",
     "codeISOAlphaTwo":"LK",
     "codeISOAlphaThree":"LKA",
     "codeISONumber":"7501"
  },
  {
     "name":"Suazilândia",
     "codeISOAlphaTwo":"SZ",
     "codeISOAlphaThree":"SWZ",
     "codeISONumber":"7544"
  },
  {
     "name":"Suécia",
     "codeISOAlphaTwo":"SE",
     "codeISOAlphaThree":"SWE",
     "codeISONumber":"7641"
  },
  {
     "name":"Suiça",
     "codeISOAlphaTwo":"CH",
     "codeISOAlphaThree":"CHE",
     "codeISONumber":"7676"
  },
  {
     "name":"Suriname",
     "codeISOAlphaTwo":"SR",
     "codeISOAlphaThree":"SUR",
     "codeISONumber":"7706"
  },
  {
     "name":"Tailândia",
     "codeISOAlphaTwo":"TH",
     "codeISOAlphaThree":"THA",
     "codeISONumber":"7765"
  },
  {
     "name":"Taiwan",
     "codeISOAlphaTwo":"TW",
     "codeISOAlphaThree":"TWN",
     "codeISONumber":"1619"
  },
  {
     "name":"Tajiquistão",
     "codeISOAlphaTwo":"TJ",
     "codeISOAlphaThree":"TJK",
     "codeISONumber":"7722"
  },
  {
     "name":"Tanzânia",
     "codeISOAlphaTwo":"TZ",
     "codeISOAlphaThree":"TZA",
     "codeISONumber":"7803"
  },
  {
     "name":"Timor-Leste",
     "codeISOAlphaTwo":"TL",
     "codeISOAlphaThree":"TLS",
     "codeISONumber":"7951"
  },
  {
     "name":"Togo",
     "codeISOAlphaTwo":"TG",
     "codeISOAlphaThree":"TGO",
     "codeISONumber":"8001"
  },
  {
     "name":"Tokelau",
     "codeISOAlphaTwo":"TK",
     "codeISOAlphaThree":"TKL",
     "codeISONumber":"8052"
  },
  {
     "name":"Tonga",
     "codeISOAlphaTwo":"TO",
     "codeISOAlphaThree":"TON",
     "codeISONumber":"8109"
  },
  {
     "name":"Trinidad e Tobago",
     "codeISOAlphaTwo":"TT",
     "codeISOAlphaThree":"TTO",
     "codeISONumber":"8150"
  },
  {
     "name":"Tunísia",
     "codeISOAlphaTwo":"TN",
     "codeISOAlphaThree":"TUN",
     "codeISONumber":"8206"
  },
  {
     "name":"Turquemenistão",
     "codeISOAlphaTwo":"TM",
     "codeISOAlphaThree":"TKM",
     "codeISONumber":"8249"
  },
  {
     "name":"Turquia",
     "codeISOAlphaTwo":"TR",
     "codeISOAlphaThree":"TUR",
     "codeISONumber":"8273"
  },
  {
     "name":"Tuvalu",
     "codeISOAlphaTwo":"TV",
     "codeISOAlphaThree":"TUV",
     "codeISONumber":"8281"
  },
  {
     "name":"Ucrânia",
     "codeISOAlphaTwo":"UA",
     "codeISOAlphaThree":"UKR",
     "codeISONumber":"8311"
  },
  {
     "name":"Uganda",
     "codeISOAlphaTwo":"UG",
     "codeISOAlphaThree":"UGA",
     "codeISONumber":"8338"
  },
  {
     "name":"Uruguai",
     "codeISOAlphaTwo":"UY",
     "codeISOAlphaThree":"URY",
     "codeISONumber":"8451"
  },
  {
     "name":"Uzbequistão",
     "codeISOAlphaTwo":"UZ",
     "codeISOAlphaThree":"UZB",
     "codeISONumber":"8478"
  },
  {
     "name":"Vanuatu",
     "codeISOAlphaTwo":"VU",
     "codeISOAlphaThree":"VUT",
     "codeISONumber":"5517"
  },
  {
     "name":"Vaticano",
     "codeISOAlphaTwo":"VA",
     "codeISOAlphaThree":"VAT",
     "codeISONumber":"8486"
  },
  {
     "name":"Venezuela",
     "codeISOAlphaTwo":"VE",
     "codeISOAlphaThree":"VEN",
     "codeISONumber":"8508"
  },
  {
     "name":"Vietnã (Vietname)",
     "codeISOAlphaTwo":"VN",
     "codeISOAlphaThree":"VNM",
     "codeISONumber":"8583"
  },
  {
     "name":"Wallis e Futuna",
     "codeISOAlphaTwo":"WF",
     "codeISOAlphaThree":"WLF",
     "codeISONumber":"8753"
  },
  {
     "name":"Zâmbia",
     "codeISOAlphaTwo":"ZM",
     "codeISOAlphaThree":"ZMB",
     "codeISONumber":"8907"
  },
  {
     "name":"Zimbabwe (Zimbabué)",
     "codeISOAlphaTwo":"ZW",
     "codeISOAlphaThree":"ZWE",
     "codeISONumber":"6653"
  }
]
