export const products: any = [
  {
    id: '1000',
    code: 'f230fh0g3',
    name: 'Bamboo Watch',
    description: 'Product Description',
    image: 'bamboo-watch.jpg',
    price: 65,
    category: 'Accessories',
    quantity: 24,
    inventoryStatus: 'INSTOCK',
    rating: 5,
  },
  {
    id: '1000',
    code: 'wefwefwef',
    name: 'Glass Statue',
    description: 'Product Description',
    image: 'bamboo-watch.jpg',
    price: 65,
    category: 'Decoration',
    quantity: 13,
    inventoryStatus: 'INSTOCK',
    rating: 5,
  },
  {
    id: '1000',
    code: 'f230fh0g3',
    name: 'Bamboo Watch',
    description: 'Product Description',
    image: 'bamboo-watch.jpg',
    price: 65,
    category: 'Accessories',
    quantity: 24,
    inventoryStatus: 'INSTOCK',
    rating: 5,
  },
  {
    id: '1000',
    code: 'wefwefwef',
    name: 'Glass Statue',
    description: 'Product Description',
    image: 'bamboo-watch.jpg',
    price: 65,
    category: 'Decoration',
    quantity: 13,
    inventoryStatus: 'INSTOCK',
    rating: 5,
  },
  {
    id: '1000',
    code: 'f230fh0g3',
    name: 'Bamboo Watch',
    description: 'Product Description',
    image: 'bamboo-watch.jpg',
    price: 65,
    category: 'Accessories',
    quantity: 24,
    inventoryStatus: 'INSTOCK',
    rating: 5,
  },
  {
    id: '1000',
    code: 'wefwefwef',
    name: 'Glass Statue',
    description: 'Product Description',
    image: 'bamboo-watch.jpg',
    price: 65,
    category: 'Decoration',
    quantity: 13,
    inventoryStatus: 'INSTOCK',
    rating: 5,
  },
];

export const opts: any = [
  {
    breakpoint: '1199px',
    numVisible: 1,
    numScroll: 1,
  },
  {
    breakpoint: '991px',
    numVisible: 2,
    numScroll: 1,
  },
  {
    breakpoint: '767px',
    numVisible: 1,
    numScroll: 1,
  },
];
